dist: trusty
language: node_js
node_js:
  - "7"
cache: npm

before_script:
  - export TZ=Europe/London
  - npm install

script:
  - npm run coverage

after_script:
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token npm run coveralls
